# Exceptional situations

Meaning `500 Internal Server Error`, `404 Not Found`, etc.

## Handling exceptions and errors

Inside `index->__construct` there is a call `$this->error->register();`.
Service error is registered as a handler for errors and exceptions.
If some exception is not caught then the service `error` would run `c_error->error()`

## Example

Running helper `notFound` will cause throwing of an exception `f_c_exception_notFound`.
The exception is caught by registered exceptions handler - service `error`.
Service `error` calls `c_error->error()`.

```php
<?php

class c_error extends f_c_action
{

    public function error()
    {

        switch (get_class($this->error->exception)) {

            case f_c_exception_notFound:
                $this->notFoundAction();
                break;

            default:
                $this->internalErrorAction();
                break;
        }

    }

    public function notFoundAction()
    {
        $this->error->render(false);

        $this->render->off();

        $this->response
            ->code(404)
            ->body("404 Not Found")
            ->send();
    }

    public function internalErrorAction()
    {
        $this->render->off();

        if ($this->env == 'dev') {
            return;
        }

        $this->response
            ->code(500)
            ->body("500 Internal Server Error")
            ->send();
    }

}

?>
```

To do: possibility to test the page /error/internalError on development server.
On development server the info about the exception is shown.

## Temporary application shutdown

In `index->__construct` we call `throw new f_c_exception_applicationOff()`.
In `c_error->error` inside switch we add `case f_c_exception_applicationOff:` where we can handle the shutdown of the application.


The same can be done with `f_c_exception_noAccess`.
It is possible to create any custom exceptions and handle them in this way.




